//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Geometry
{
    [Serializable]
    public class VelocityWithCovarianceStampedMsg : Message
    {
        public const string k_RosMessageName = "geometry_msgs/VelocityWithCovarianceStamped";
        public override string RosMessageName => k_RosMessageName;

        //  A timestamped velocity of a body whose frame is 'body_frame_id', measured
        //  relative to the reference frame 'reference_frame_id', with the velocity and
        //  covariance both expressed in the basis of the observation frame
        //  'header.frame_id'.
        // 
        //  - If 'body_frame_id' and 'header.frame_id' are identical, the velocity and
        //    covariance are expressed in the body's own basis. This is functionally
        //    equivalent to the body-twist convention used by
        //    'geometry_msgs/TwistStamped'.
        // 
        //  This message is the covariance-bearing analogue of
        //  'geometry_msgs/VelocityStamped'.
        public Std.HeaderMsg header;
        public string body_frame_id;
        public string reference_frame_id;
        public TwistWithCovarianceMsg velocity;

        public VelocityWithCovarianceStampedMsg()
        {
            this.header = new Std.HeaderMsg();
            this.body_frame_id = "";
            this.reference_frame_id = "";
            this.velocity = new TwistWithCovarianceMsg();
        }

        public VelocityWithCovarianceStampedMsg(Std.HeaderMsg header, string body_frame_id, string reference_frame_id, TwistWithCovarianceMsg velocity)
        {
            this.header = header;
            this.body_frame_id = body_frame_id;
            this.reference_frame_id = reference_frame_id;
            this.velocity = velocity;
        }

        public static VelocityWithCovarianceStampedMsg Deserialize(MessageDeserializer deserializer) => new VelocityWithCovarianceStampedMsg(deserializer);

        private VelocityWithCovarianceStampedMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.body_frame_id);
            deserializer.Read(out this.reference_frame_id);
            this.velocity = TwistWithCovarianceMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.body_frame_id);
            serializer.Write(this.reference_frame_id);
            serializer.Write(this.velocity);
        }

        public override string ToString()
        {
            return "VelocityWithCovarianceStampedMsg: " +
            "\nheader: " + header.ToString() +
            "\nbody_frame_id: " + body_frame_id.ToString() +
            "\nreference_frame_id: " + reference_frame_id.ToString() +
            "\nvelocity: " + velocity.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
